services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: love
      POSTGRES_DB: csv
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    networks: 
      - default
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: